version: "3.9"
services:
  app:
    image: mysql
    container_name: ticket_system
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password